### PR TITLE
replaced gets

### PR DESCRIPTION
**Pull request by TanmayAgrawal**

### CODE REVIEW

**Review by twitu — CHANGES_REQUESTED** [review]
You have deleted the entire file. Please change the function in place i.e. add the modified code to `bulk_input()` function at line 179

**Comment by twitu** [comment]
Also please use github CLI to make commits

**Review by TanmayAgrawal — COMMENTED** [review]
Sorry for the mistake.I have corrected it

**Review by twitu — CHANGES_REQUESTED** [review]
use github CLI, the web interface overwrites the entire file
also refrain from using regex in this case, instead use fgets or getline

**Comment by twitu** [comment]
Please make a separate pull request after making the changes, follow this [tutorial](https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project) for help

**Pull request closed without merging**
